name: Go Tests
on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./demo-golang-tf
    steps:
      - uses: actions/checkout@v4

      - name: ðŸ“¦ Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: ðŸ“¦ Install dependencies
        run: go mod download

      - name: ðŸ“¦ Install gotestsum
        run: |
          go install gotest.tools/gotestsum@latest
          export PATH=$PATH:~/go/bin

      - name: ðŸ§ª Run tests
        run: gotestsum --junitfile test-results.xml -- ./test/...

      - name: Report Results
        if: true
        uses: testfiesta/tacotruck-action@v1
        with:
          provider: testfiesta
          handle: handle
          project: project
          run-name: Go testing CI run
          base-url: https://staging.api.testfiesta.com
          credentials: ${{ secrets.TESTFIESTA_API_KEY }}
          results-path: ./demo-golang-tf/test-results.xml
